---
- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
      - name: Get the current caller identity information
        amazon.aws.aws_caller_info:
        register: caller_user_id

      - name: Show caller identity
        debug:
          msg: "The current role is {{ caller_user_id }}"
      - name: get secret
        set_fact:
          secret: "{{ lookup('aws_ssm', '/tests/karol/ansible_secret', region='eu-central-1') }}"
      - name: print secret
        debug:
          var: secret
          
---
- name: Set secret for awsdemo-ada-001
  set_fact:
    db_password: "{{ secret }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['awsdemo-ada-001'] }}"
