---
- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Assume role
      sts_assume_role:
        role_arn: "arn:aws:iam::809959423725:role/awx-dev-awx-iam-role-awx"
        role_session_name: "AnsibleSession"
      register: assumed_role
      
    - name: Get the current caller identity information
      amazon.aws.aws_caller_info:
      register: caller_user_id

    - name: Show caller identity
      debug:
        msg: "The current role is {{ caller_user_id }}"
    - name: get secret
      set_fact:
        secret: "{{ lookup('aws_ssm', '/tests/karol/ansible_secret', region='eu-central-1') }}"
  
    - name: Set secret for awsdemo-ada-001
      set_fact:
        db_password: "{{ secret }}"
      delegate_to: "{{ item }}"
      loop: "{{ groups['awsdemo-ada-001'] }}"

- name: Display the secret
  hosts: 'awsdemo-ada-001'
  gather_facts: False
  tasks:
    - name: print secret
      debug:
        var: db_password
