---
- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Assume role
      community.aws.sts_assume_role:
        role_arn: "arn:aws:iam::809959423725:role/awx-dev-awx-iam-role-awx"
        role_session_name: "AnsibleSession"
      register: assumed_role
