---
- name: Get password from SSM
  hosts: localhost
  gather_facts: false
  tasks:
      - name: get secret
        set_stats:
          data:
            shared_secret: "{{ lookup('aws_ssm', '/tests/karol/ansible_secret', region='eu-central-1') }}"
