---
- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
    - name: get secret
      set_fact:
        secret: "{{ lookup('aws_ssm', '/tests/karol/ansible_secret', region='eu-central-1') }}"
  
    - name: Set secret for awsdemo-ada-001
      set_fact:
        db_password: "{{ secret }}"
      delegate_to: "{{ item }}"
      loop: "{{ groups['awsdemo-ada-001'] }}"

- name: Display the secret
  hosts: 'awsdemo-ada-001'
  gather_facts: False
  tasks:
    - name: print secret
      debug:
        var: db_password
