---
- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
      - name: get secret
        set_fact:
          secret: "{{ lookup('aws_ssm', '/tests/karol/ansible_secret', region='eu-central-1') }}"

      - name: Add secret to credential store
        awx.awx.credential:
          name: test_credential
          organization: Default
          credential_type: Vault
          inputs:
            vault_password: "{{ secret }}"