---
- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
    - community.aws.sts_assume_role:
      role_arn: "arn:aws:iam::809959423725:role/awx-dev-awx-iam-role-awx"
      role_session_name: "AnsibleSession"
