- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
      - name: get secret
        set_fact:
          secret: "{{ lookup('aws_ssm', '/tests/karol/ansible_secret', region='eu-central-1') }}"
        delegate_to: "{{ item }}"
        loop: "{{ groups['public_tests'] }}"

      - name: Add secret to credential store
        awx.awx.credential:
          name: test_credential
          organization: Default
          credential_type: Database password
          inputs:
            db_pass: "{{ secret }}"

- name: Windows dummy task
  hosts: public_tests

  tasks:
    - name: Show the output
      debug:
        msg: "The secret is {{ secret }}"
