---
- name: Get password from SSM
  hosts: localhost
  gather_facts: False
  tasks:
    - name: get secret
      set_fact:
        secret: "{{ lookup('aws_ssm', '/tests/karol/ansible_secret', region='eu-central-1') }}"

- name: Set secret on hosts
  hosts: public_tests
  gather_facts: False
  tasks:
    - name: set secret
      set_fact:
        secret: "{{ hostvars['localhost'].secret }}"
      
- name: Windows dummy task
  hosts: public_tests
  tasks:
    - name: Show the output
      debug:
        msg: "The secret is {{ secret }}"
